/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AguardandoAprovacaoRouteImport } from './routes/aguardando-aprovacao'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAgendaRouteImport } from './routes/_app/agenda'
import { Route as AppClientesRouteImport } from './routes/_app/clientes'
import { Route as AppEstoqueRouteImport } from './routes/_app/estoque'
import { Route as AppFinanceiroRouteImport } from './routes/_app/financeiro'
import { Route as AppGaragemRouteImport } from './routes/_app/garagem'
import { Route as AppMenuRouteImport } from './routes/_app/menu'
import { Route as AppNotificacoesRouteImport } from './routes/_app/notificacoes'
import { Route as AppPerfilRouteImport } from './routes/_app/perfil'
import { Route as AppServicosRouteImport } from './routes/_app/servicos'
import { Route as AppVendidosRouteImport } from './routes/_app/vendidos'
import { Route as AppAgendaNovoRouteImport } from './routes/_app/agenda.novo'
import { Route as AppClientesNovoRouteImport } from './routes/_app/clientes.novo'
import { Route as AppEstoqueNovoRouteImport } from './routes/_app/estoque.novo'
import { Route as AppGaragemTruckIdRouteImport } from './routes/_app/garagem.$truckId'
import { Route as AppGaragemNovoRouteImport } from './routes/_app/garagem.novo'
import { Route as AppServicosNovoRouteImport } from './routes/_app/servicos.novo'
import { Route as AppGaragemTruckIdDespesaRouteImport } from './routes/_app/garagem.$truckId.despesa'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AguardandoAprovacaoRoute = AguardandoAprovacaoRouteImport.update({
  id: '/aguardando-aprovacao',
  path: '/aguardando-aprovacao',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppGaragemRoute = AppGaragemRouteImport.update({
  id: '/garagem',
  path: '/garagem',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuRoute = AppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppServicosRoute = AppServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AppRoute,
} as any)
const AppVendidosRoute = AppVendidosRouteImport.update({
  id: '/vendidos',
  path: '/vendidos',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaNovoRoute = AppAgendaNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppAgendaRoute,
} as any)
const AppClientesNovoRoute = AppClientesNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppClientesRoute,
} as any)
const AppEstoqueNovoRoute = AppEstoqueNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppEstoqueRoute,
} as any)
const AppGaragemTruckIdRoute = AppGaragemTruckIdRouteImport.update({
  id: '/$truckId',
  path: '/$truckId',
  getParentRoute: () => AppGaragemRoute,
} as any)
const AppGaragemNovoRoute = AppGaragemNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppGaragemRoute,
} as any)
const AppServicosNovoRoute = AppServicosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppServicosRoute,
} as any)
const AppGaragemTruckIdDespesaRoute =
  AppGaragemTruckIdDespesaRouteImport.update({
    id: '/despesa',
    path: '/despesa',
    getParentRoute: () => AppGaragemTruckIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRouteWithChildren
  '/clientes': typeof AppClientesRouteWithChildren
  '/estoque': typeof AppEstoqueRouteWithChildren
  '/financeiro': typeof AppFinanceiroRoute
  '/garagem': typeof AppGaragemRouteWithChildren
  '/menu': typeof AppMenuRoute
  '/notificacoes': typeof AppNotificacoesRoute
  '/perfil': typeof AppPerfilRoute
  '/servicos': typeof AppServicosRouteWithChildren
  '/vendidos': typeof AppVendidosRoute
  '/agenda/novo': typeof AppAgendaNovoRoute
  '/clientes/novo': typeof AppClientesNovoRoute
  '/estoque/novo': typeof AppEstoqueNovoRoute
  '/garagem/$truckId': typeof AppGaragemTruckIdRouteWithChildren
  '/garagem/novo': typeof AppGaragemNovoRoute
  '/servicos/novo': typeof AppServicosNovoRoute
  '/garagem/$truckId/despesa': typeof AppGaragemTruckIdDespesaRoute
}
export interface FileRoutesByTo {
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRouteWithChildren
  '/clientes': typeof AppClientesRouteWithChildren
  '/estoque': typeof AppEstoqueRouteWithChildren
  '/financeiro': typeof AppFinanceiroRoute
  '/garagem': typeof AppGaragemRouteWithChildren
  '/menu': typeof AppMenuRoute
  '/notificacoes': typeof AppNotificacoesRoute
  '/perfil': typeof AppPerfilRoute
  '/servicos': typeof AppServicosRouteWithChildren
  '/vendidos': typeof AppVendidosRoute
  '/': typeof AppIndexRoute
  '/agenda/novo': typeof AppAgendaNovoRoute
  '/clientes/novo': typeof AppClientesNovoRoute
  '/estoque/novo': typeof AppEstoqueNovoRoute
  '/garagem/$truckId': typeof AppGaragemTruckIdRouteWithChildren
  '/garagem/novo': typeof AppGaragemNovoRoute
  '/servicos/novo': typeof AppServicosNovoRoute
  '/garagem/$truckId/despesa': typeof AppGaragemTruckIdDespesaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/_app/agenda': typeof AppAgendaRouteWithChildren
  '/_app/clientes': typeof AppClientesRouteWithChildren
  '/_app/estoque': typeof AppEstoqueRouteWithChildren
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/garagem': typeof AppGaragemRouteWithChildren
  '/_app/menu': typeof AppMenuRoute
  '/_app/notificacoes': typeof AppNotificacoesRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/servicos': typeof AppServicosRouteWithChildren
  '/_app/vendidos': typeof AppVendidosRoute
  '/_app/': typeof AppIndexRoute
  '/_app/agenda/novo': typeof AppAgendaNovoRoute
  '/_app/clientes/novo': typeof AppClientesNovoRoute
  '/_app/estoque/novo': typeof AppEstoqueNovoRoute
  '/_app/garagem/$truckId': typeof AppGaragemTruckIdRouteWithChildren
  '/_app/garagem/novo': typeof AppGaragemNovoRoute
  '/_app/servicos/novo': typeof AppServicosNovoRoute
  '/_app/garagem/$truckId/despesa': typeof AppGaragemTruckIdDespesaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aguardando-aprovacao'
    | '/cadastro'
    | '/login'
    | '/agenda'
    | '/clientes'
    | '/estoque'
    | '/financeiro'
    | '/garagem'
    | '/menu'
    | '/notificacoes'
    | '/perfil'
    | '/servicos'
    | '/vendidos'
    | '/agenda/novo'
    | '/clientes/novo'
    | '/estoque/novo'
    | '/garagem/$truckId'
    | '/garagem/novo'
    | '/servicos/novo'
    | '/garagem/$truckId/despesa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/aguardando-aprovacao'
    | '/cadastro'
    | '/login'
    | '/agenda'
    | '/clientes'
    | '/estoque'
    | '/financeiro'
    | '/garagem'
    | '/menu'
    | '/notificacoes'
    | '/perfil'
    | '/servicos'
    | '/vendidos'
    | '/'
    | '/agenda/novo'
    | '/clientes/novo'
    | '/estoque/novo'
    | '/garagem/$truckId'
    | '/garagem/novo'
    | '/servicos/novo'
    | '/garagem/$truckId/despesa'
  id:
    | '__root__'
    | '/_app'
    | '/aguardando-aprovacao'
    | '/cadastro'
    | '/login'
    | '/_app/agenda'
    | '/_app/clientes'
    | '/_app/estoque'
    | '/_app/financeiro'
    | '/_app/garagem'
    | '/_app/menu'
    | '/_app/notificacoes'
    | '/_app/perfil'
    | '/_app/servicos'
    | '/_app/vendidos'
    | '/_app/'
    | '/_app/agenda/novo'
    | '/_app/clientes/novo'
    | '/_app/estoque/novo'
    | '/_app/garagem/$truckId'
    | '/_app/garagem/novo'
    | '/_app/servicos/novo'
    | '/_app/garagem/$truckId/despesa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AguardandoAprovacaoRoute: typeof AguardandoAprovacaoRoute
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aguardando-aprovacao': {
      id: '/aguardando-aprovacao'
      path: '/aguardando-aprovacao'
      fullPath: '/aguardando-aprovacao'
      preLoaderRoute: typeof AguardandoAprovacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque': {
      id: '/_app/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/garagem': {
      id: '/_app/garagem'
      path: '/garagem'
      fullPath: '/garagem'
      preLoaderRoute: typeof AppGaragemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu': {
      id: '/_app/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AppMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notificacoes': {
      id: '/_app/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servicos': {
      id: '/_app/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AppServicosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendidos': {
      id: '/_app/vendidos'
      path: '/vendidos'
      fullPath: '/vendidos'
      preLoaderRoute: typeof AppVendidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda/novo': {
      id: '/_app/agenda/novo'
      path: '/novo'
      fullPath: '/agenda/novo'
      preLoaderRoute: typeof AppAgendaNovoRouteImport
      parentRoute: typeof AppAgendaRoute
    }
    '/_app/clientes/novo': {
      id: '/_app/clientes/novo'
      path: '/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof AppClientesNovoRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/_app/estoque/novo': {
      id: '/_app/estoque/novo'
      path: '/novo'
      fullPath: '/estoque/novo'
      preLoaderRoute: typeof AppEstoqueNovoRouteImport
      parentRoute: typeof AppEstoqueRoute
    }
    '/_app/garagem/$truckId': {
      id: '/_app/garagem/$truckId'
      path: '/$truckId'
      fullPath: '/garagem/$truckId'
      preLoaderRoute: typeof AppGaragemTruckIdRouteImport
      parentRoute: typeof AppGaragemRoute
    }
    '/_app/garagem/novo': {
      id: '/_app/garagem/novo'
      path: '/novo'
      fullPath: '/garagem/novo'
      preLoaderRoute: typeof AppGaragemNovoRouteImport
      parentRoute: typeof AppGaragemRoute
    }
    '/_app/servicos/novo': {
      id: '/_app/servicos/novo'
      path: '/novo'
      fullPath: '/servicos/novo'
      preLoaderRoute: typeof AppServicosNovoRouteImport
      parentRoute: typeof AppServicosRoute
    }
    '/_app/garagem/$truckId/despesa': {
      id: '/_app/garagem/$truckId/despesa'
      path: '/despesa'
      fullPath: '/garagem/$truckId/despesa'
      preLoaderRoute: typeof AppGaragemTruckIdDespesaRouteImport
      parentRoute: typeof AppGaragemTruckIdRoute
    }
  }
}

interface AppAgendaRouteChildren {
  AppAgendaNovoRoute: typeof AppAgendaNovoRoute
}

const AppAgendaRouteChildren: AppAgendaRouteChildren = {
  AppAgendaNovoRoute: AppAgendaNovoRoute,
}

const AppAgendaRouteWithChildren = AppAgendaRoute._addFileChildren(
  AppAgendaRouteChildren,
)

interface AppClientesRouteChildren {
  AppClientesNovoRoute: typeof AppClientesNovoRoute
}

const AppClientesRouteChildren: AppClientesRouteChildren = {
  AppClientesNovoRoute: AppClientesNovoRoute,
}

const AppClientesRouteWithChildren = AppClientesRoute._addFileChildren(
  AppClientesRouteChildren,
)

interface AppEstoqueRouteChildren {
  AppEstoqueNovoRoute: typeof AppEstoqueNovoRoute
}

const AppEstoqueRouteChildren: AppEstoqueRouteChildren = {
  AppEstoqueNovoRoute: AppEstoqueNovoRoute,
}

const AppEstoqueRouteWithChildren = AppEstoqueRoute._addFileChildren(
  AppEstoqueRouteChildren,
)

interface AppGaragemTruckIdRouteChildren {
  AppGaragemTruckIdDespesaRoute: typeof AppGaragemTruckIdDespesaRoute
}

const AppGaragemTruckIdRouteChildren: AppGaragemTruckIdRouteChildren = {
  AppGaragemTruckIdDespesaRoute: AppGaragemTruckIdDespesaRoute,
}

const AppGaragemTruckIdRouteWithChildren =
  AppGaragemTruckIdRoute._addFileChildren(AppGaragemTruckIdRouteChildren)

interface AppGaragemRouteChildren {
  AppGaragemTruckIdRoute: typeof AppGaragemTruckIdRouteWithChildren
  AppGaragemNovoRoute: typeof AppGaragemNovoRoute
}

const AppGaragemRouteChildren: AppGaragemRouteChildren = {
  AppGaragemTruckIdRoute: AppGaragemTruckIdRouteWithChildren,
  AppGaragemNovoRoute: AppGaragemNovoRoute,
}

const AppGaragemRouteWithChildren = AppGaragemRoute._addFileChildren(
  AppGaragemRouteChildren,
)

interface AppServicosRouteChildren {
  AppServicosNovoRoute: typeof AppServicosNovoRoute
}

const AppServicosRouteChildren: AppServicosRouteChildren = {
  AppServicosNovoRoute: AppServicosNovoRoute,
}

const AppServicosRouteWithChildren = AppServicosRoute._addFileChildren(
  AppServicosRouteChildren,
)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRouteWithChildren
  AppClientesRoute: typeof AppClientesRouteWithChildren
  AppEstoqueRoute: typeof AppEstoqueRouteWithChildren
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppGaragemRoute: typeof AppGaragemRouteWithChildren
  AppMenuRoute: typeof AppMenuRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppServicosRoute: typeof AppServicosRouteWithChildren
  AppVendidosRoute: typeof AppVendidosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRouteWithChildren,
  AppClientesRoute: AppClientesRouteWithChildren,
  AppEstoqueRoute: AppEstoqueRouteWithChildren,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppGaragemRoute: AppGaragemRouteWithChildren,
  AppMenuRoute: AppMenuRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppServicosRoute: AppServicosRouteWithChildren,
  AppVendidosRoute: AppVendidosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AguardandoAprovacaoRoute: AguardandoAprovacaoRoute,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
